//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Maraton", "Maraton", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TPFinalWeb3.Maraton), "ResultadoMaratonParticipante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TPFinalWeb3.ResultadoMaratonParticipante), true)]
[assembly: EdmRelationshipAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TPFinalWeb3.Usuario), "ResultadoMaratonParticipante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TPFinalWeb3.ResultadoMaratonParticipante), true)]

#endregion

namespace TPFinalWeb3
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PW3_20152C_TP2_MaratonesEntities3 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PW3_20152C_TP2_MaratonesEntities3 usando la cadena de conexión encontrada en la sección 'PW3_20152C_TP2_MaratonesEntities3' del archivo de configuración de la aplicación.
        /// </summary>
        public PW3_20152C_TP2_MaratonesEntities3() : base("name=PW3_20152C_TP2_MaratonesEntities3", "PW3_20152C_TP2_MaratonesEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PW3_20152C_TP2_MaratonesEntities3.
        /// </summary>
        public PW3_20152C_TP2_MaratonesEntities3(string connectionString) : base(connectionString, "PW3_20152C_TP2_MaratonesEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PW3_20152C_TP2_MaratonesEntities3.
        /// </summary>
        public PW3_20152C_TP2_MaratonesEntities3(EntityConnection connection) : base(connection, "PW3_20152C_TP2_MaratonesEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Maraton> Maraton
        {
            get
            {
                if ((_Maraton == null))
                {
                    _Maraton = base.CreateObjectSet<Maraton>("Maraton");
                }
                return _Maraton;
            }
        }
        private ObjectSet<Maraton> _Maraton;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ResultadoMaratonParticipante> ResultadoMaratonParticipante
        {
            get
            {
                if ((_ResultadoMaratonParticipante == null))
                {
                    _ResultadoMaratonParticipante = base.CreateObjectSet<ResultadoMaratonParticipante>("ResultadoMaratonParticipante");
                }
                return _ResultadoMaratonParticipante;
            }
        }
        private ObjectSet<ResultadoMaratonParticipante> _ResultadoMaratonParticipante;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Maraton. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMaraton(Maraton maraton)
        {
            base.AddObject("Maraton", maraton);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ResultadoMaratonParticipante. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToResultadoMaratonParticipante(ResultadoMaratonParticipante resultadoMaratonParticipante)
        {
            base.AddObject("ResultadoMaratonParticipante", resultadoMaratonParticipante);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_MaratonesModel3", Name="Maraton")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Maraton : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Maraton.
        /// </summary>
        /// <param name="idMaraton">Valor inicial de la propiedad IdMaraton.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="maxParticipantes">Valor inicial de la propiedad MaxParticipantes.</param>
        /// <param name="lugarSalida">Valor inicial de la propiedad LugarSalida.</param>
        /// <param name="participantesEnEspera">Valor inicial de la propiedad ParticipantesEnEspera.</param>
        /// <param name="primerPremio">Valor inicial de la propiedad PrimerPremio.</param>
        /// <param name="segundoPremio">Valor inicial de la propiedad SegundoPremio.</param>
        /// <param name="tercerPremio">Valor inicial de la propiedad TercerPremio.</param>
        public static Maraton CreateMaraton(global::System.Int32 idMaraton, global::System.String nombre, global::System.Int32 maxParticipantes, global::System.String lugarSalida, global::System.Int32 participantesEnEspera, global::System.Int32 primerPremio, global::System.Int32 segundoPremio, global::System.Int32 tercerPremio)
        {
            Maraton maraton = new Maraton();
            maraton.IdMaraton = idMaraton;
            maraton.Nombre = nombre;
            maraton.MaxParticipantes = maxParticipantes;
            maraton.LugarSalida = lugarSalida;
            maraton.ParticipantesEnEspera = participantesEnEspera;
            maraton.PrimerPremio = primerPremio;
            maraton.SegundoPremio = segundoPremio;
            maraton.TercerPremio = tercerPremio;
            return maraton;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMaraton
        {
            get
            {
                return _IdMaraton;
            }
            set
            {
                if (_IdMaraton != value)
                {
                    OnIdMaratonChanging(value);
                    ReportPropertyChanging("IdMaraton");
                    _IdMaraton = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMaraton");
                    OnIdMaratonChanged();
                }
            }
        }
        private global::System.Int32 _IdMaraton;
        partial void OnIdMaratonChanging(global::System.Int32 value);
        partial void OnIdMaratonChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxParticipantes
        {
            get
            {
                return _MaxParticipantes;
            }
            set
            {
                OnMaxParticipantesChanging(value);
                ReportPropertyChanging("MaxParticipantes");
                _MaxParticipantes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxParticipantes");
                OnMaxParticipantesChanged();
            }
        }
        private global::System.Int32 _MaxParticipantes;
        partial void OnMaxParticipantesChanging(global::System.Int32 value);
        partial void OnMaxParticipantesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LugarSalida
        {
            get
            {
                return _LugarSalida;
            }
            set
            {
                OnLugarSalidaChanging(value);
                ReportPropertyChanging("LugarSalida");
                _LugarSalida = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LugarSalida");
                OnLugarSalidaChanged();
            }
        }
        private global::System.String _LugarSalida;
        partial void OnLugarSalidaChanging(global::System.String value);
        partial void OnLugarSalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParticipantesEnEspera
        {
            get
            {
                return _ParticipantesEnEspera;
            }
            set
            {
                OnParticipantesEnEsperaChanging(value);
                ReportPropertyChanging("ParticipantesEnEspera");
                _ParticipantesEnEspera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParticipantesEnEspera");
                OnParticipantesEnEsperaChanged();
            }
        }
        private global::System.Int32 _ParticipantesEnEspera;
        partial void OnParticipantesEnEsperaChanging(global::System.Int32 value);
        partial void OnParticipantesEnEsperaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrimerPremio
        {
            get
            {
                return _PrimerPremio;
            }
            set
            {
                OnPrimerPremioChanging(value);
                ReportPropertyChanging("PrimerPremio");
                _PrimerPremio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrimerPremio");
                OnPrimerPremioChanged();
            }
        }
        private global::System.Int32 _PrimerPremio;
        partial void OnPrimerPremioChanging(global::System.Int32 value);
        partial void OnPrimerPremioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SegundoPremio
        {
            get
            {
                return _SegundoPremio;
            }
            set
            {
                OnSegundoPremioChanging(value);
                ReportPropertyChanging("SegundoPremio");
                _SegundoPremio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SegundoPremio");
                OnSegundoPremioChanged();
            }
        }
        private global::System.Int32 _SegundoPremio;
        partial void OnSegundoPremioChanging(global::System.Int32 value);
        partial void OnSegundoPremioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TercerPremio
        {
            get
            {
                return _TercerPremio;
            }
            set
            {
                OnTercerPremioChanging(value);
                ReportPropertyChanging("TercerPremio");
                _TercerPremio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TercerPremio");
                OnTercerPremioChanged();
            }
        }
        private global::System.Int32 _TercerPremio;
        partial void OnTercerPremioChanging(global::System.Int32 value);
        partial void OnTercerPremioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHorarioComienzo
        {
            get
            {
                return _FechaHorarioComienzo;
            }
            set
            {
                OnFechaHorarioComienzoChanging(value);
                ReportPropertyChanging("FechaHorarioComienzo");
                _FechaHorarioComienzo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHorarioComienzo");
                OnFechaHorarioComienzoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHorarioComienzo;
        partial void OnFechaHorarioComienzoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHorarioComienzoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Maraton", "ResultadoMaratonParticipante")]
        public EntityCollection<ResultadoMaratonParticipante> ResultadoMaratonParticipante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ResultadoMaratonParticipante>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "ResultadoMaratonParticipante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ResultadoMaratonParticipante>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "ResultadoMaratonParticipante", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_MaratonesModel3", Name="ResultadoMaratonParticipante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ResultadoMaratonParticipante : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ResultadoMaratonParticipante.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de la propiedad IdUsuario.</param>
        /// <param name="idMaraton">Valor inicial de la propiedad IdMaraton.</param>
        /// <param name="nroInscripcion">Valor inicial de la propiedad NroInscripcion.</param>
        public static ResultadoMaratonParticipante CreateResultadoMaratonParticipante(global::System.Int32 idUsuario, global::System.Int32 idMaraton, global::System.Int32 nroInscripcion)
        {
            ResultadoMaratonParticipante resultadoMaratonParticipante = new ResultadoMaratonParticipante();
            resultadoMaratonParticipante.IdUsuario = idUsuario;
            resultadoMaratonParticipante.IdMaraton = idMaraton;
            resultadoMaratonParticipante.NroInscripcion = nroInscripcion;
            return resultadoMaratonParticipante;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMaraton
        {
            get
            {
                return _IdMaraton;
            }
            set
            {
                if (_IdMaraton != value)
                {
                    OnIdMaratonChanging(value);
                    ReportPropertyChanging("IdMaraton");
                    _IdMaraton = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMaraton");
                    OnIdMaratonChanged();
                }
            }
        }
        private global::System.Int32 _IdMaraton;
        partial void OnIdMaratonChanging(global::System.Int32 value);
        partial void OnIdMaratonChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NroInscripcion
        {
            get
            {
                return _NroInscripcion;
            }
            set
            {
                OnNroInscripcionChanging(value);
                ReportPropertyChanging("NroInscripcion");
                _NroInscripcion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NroInscripcion");
                OnNroInscripcionChanged();
            }
        }
        private global::System.Int32 _NroInscripcion;
        partial void OnNroInscripcionChanging(global::System.Int32 value);
        partial void OnNroInscripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PosicionFinal
        {
            get
            {
                return _PosicionFinal;
            }
            set
            {
                OnPosicionFinalChanging(value);
                ReportPropertyChanging("PosicionFinal");
                _PosicionFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PosicionFinal");
                OnPosicionFinalChanged();
            }
        }
        private Nullable<global::System.Int32> _PosicionFinal;
        partial void OnPosicionFinalChanging(Nullable<global::System.Int32> value);
        partial void OnPosicionFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TiempoLlegada
        {
            get
            {
                return _TiempoLlegada;
            }
            set
            {
                OnTiempoLlegadaChanging(value);
                ReportPropertyChanging("TiempoLlegada");
                _TiempoLlegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TiempoLlegada");
                OnTiempoLlegadaChanged();
            }
        }
        private Nullable<global::System.Int32> _TiempoLlegada;
        partial void OnTiempoLlegadaChanging(Nullable<global::System.Int32> value);
        partial void OnTiempoLlegadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Finalizo
        {
            get
            {
                return _Finalizo;
            }
            set
            {
                OnFinalizoChanging(value);
                ReportPropertyChanging("Finalizo");
                _Finalizo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Finalizo");
                OnFinalizoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Finalizo;
        partial void OnFinalizoChanging(Nullable<global::System.Boolean> value);
        partial void OnFinalizoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Maraton", "Maraton")]
        public Maraton Maraton
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Maraton>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "Maraton").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Maraton>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "Maraton").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Maraton> MaratonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Maraton>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "Maraton");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Maraton>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Maraton", "Maraton", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_MaratonesModel3", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de la propiedad IdUsuario.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        /// <param name="contrasenia">Valor inicial de la propiedad Contrasenia.</param>
        /// <param name="admin">Valor inicial de la propiedad Admin.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="fechaNac">Valor inicial de la propiedad FechaNac.</param>
        /// <param name="lugarResidencia">Valor inicial de la propiedad LugarResidencia.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String email, global::System.String contrasenia, global::System.Boolean admin, global::System.String nombre, global::System.String apellido, global::System.DateTime fechaNac, global::System.String lugarResidencia)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = idUsuario;
            usuario.Email = email;
            usuario.Contrasenia = contrasenia;
            usuario.Admin = admin;
            usuario.Nombre = nombre;
            usuario.Apellido = apellido;
            usuario.FechaNac = fechaNac;
            usuario.LugarResidencia = lugarResidencia;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contrasenia
        {
            get
            {
                return _Contrasenia;
            }
            set
            {
                OnContraseniaChanging(value);
                ReportPropertyChanging("Contrasenia");
                _Contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contrasenia");
                OnContraseniaChanged();
            }
        }
        private global::System.String _Contrasenia;
        partial void OnContraseniaChanging(global::System.String value);
        partial void OnContraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Boolean _Admin;
        partial void OnAdminChanging(global::System.Boolean value);
        partial void OnAdminChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaNac
        {
            get
            {
                return _FechaNac;
            }
            set
            {
                OnFechaNacChanging(value);
                ReportPropertyChanging("FechaNac");
                _FechaNac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNac");
                OnFechaNacChanged();
            }
        }
        private global::System.DateTime _FechaNac;
        partial void OnFechaNacChanging(global::System.DateTime value);
        partial void OnFechaNacChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LugarResidencia
        {
            get
            {
                return _LugarResidencia;
            }
            set
            {
                OnLugarResidenciaChanging(value);
                ReportPropertyChanging("LugarResidencia");
                _LugarResidencia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LugarResidencia");
                OnLugarResidenciaChanged();
            }
        }
        private global::System.String _LugarResidencia;
        partial void OnLugarResidenciaChanging(global::System.String value);
        partial void OnLugarResidenciaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_MaratonesModel3", "FK_ResultadoMaratonParticipante_Usuario", "ResultadoMaratonParticipante")]
        public EntityCollection<ResultadoMaratonParticipante> ResultadoMaratonParticipante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ResultadoMaratonParticipante>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "ResultadoMaratonParticipante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ResultadoMaratonParticipante>("PW3_20152C_TP2_MaratonesModel3.FK_ResultadoMaratonParticipante_Usuario", "ResultadoMaratonParticipante", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
